config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  namespace :competition_result do
    resources :run_records
  end
  namespace :practice do
    resources :run_records
  end
  devise_for :users, controllers:{
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks#sns_login"
  }
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :competition_infos, only:[:new, :create, :index] do
    collection do
      get 'search'
    end
  end
  resources :user_comp_schedules, only:[:create]
  resources :boards, shallow: true do
    resources :comments, only:[:create, :edit, :update, :destroy]
  end
  resources :users, only:[:index, :show] do
    collection do
      get 'recent_run_record'
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @users = User.all.order(created_at: "DESC").first(6)
    @run_records = RunRecord.recent_run_record_find(@users)
  end
end

app/views/top/index.html.haml
.jumbotron.jumbotron-extend
  .jumbotron-title
    No Run, No Life
.inline-block
  %h3= t '.recent_create_user'
  - unless @users.blank?
    = link_to "(#{t '.user_all'})", users_path
  - else
    #{t '.no_user'}
  %ol.info-box
    - @users.each do |user|
      %li
        = t '.user_name'
        = ":"
        = link_to user.name, user_path(user.id)
        = t '.created_at'
        = ":"
        = user.created_at.strftime("%Y-%m-%d")
.inline-block
  %h3= t '.about_app'
  %ol.info-box
    %li= t '.management'
    %li= t '.googlemap'
    %li= t '.competition_search'
    %li= t '.csv'
    %li= t '.board'
    %li= t '.run_level'
.inline-block
  %h3= t '.recent_contribution'
  - unless @run_records.blank?
    = link_to "(#{t '.everyone_record'})", recent_run_record_users_path
    = render 'shared/recent_contribution_list', run_records: @run_records
  - else
    #{t '.no_contribution'}