config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  namespace :competition_result do
    resources :run_records
  end
  namespace :practice do
    resources :run_records
  end
  devise_for :users, controllers:{
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks#sns_login"
  }
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :competition_infos, only:[:new, :create, :index] do
    collection do
      get 'search'
    end
  end
  resources :user_comp_schedules, only:[:create]
  resources :boards, shallow: true do
    resources :comments, only:[:create, :edit, :update, :destroy]
  end
  resources :users, only:[:index, :show] do
    collection do
      get 'recent_run_record'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable, :omniauthable

  has_many :run_records, dependent: :destroy
  has_many :user_comp_schedules, dependent: :destroy
  has_many :competition_infos, through: :user_comp_schedules
  has_many :comments, dependent: :destroy
  has_many :boards, dependent: :destroy

  validates :name, presence: true

  def self.find_userinfo(auth)
    user = User.find_by(provider: auth.provider, userid: auth.uid)

    if user.nil?
        user = User.new(
          email: "#{auth.uid}@#{auth.provider}.com",
          provider: auth.provider,
          userid: auth.uid,
          name: auth.info.name,
          password: Devise.friendly_token[0,20]
        )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_uuid
    SecureRandom.uuid
  end

  def self.run_level_up_decision(user_id)
    user = User.find(user_id)
    user.total_run_experience = user.run_records.sum(:run_distance)

    if user.total_run_experience > RunExperience.find_by(run_level: user.run_level.to_i + 1).need_experience_point
      user.run_level += 1
    end
    user.save
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def sns_login
    @user = User.find_userinfo(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = t('devise.sessions.signed_in')
      sign_in_and_redirect @user, event: :authentication
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  def build_resource(hash = nil)
    hash[:userid] = User.create_uuid
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys:[:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.page(params[:page]).per(10).order(created_at: "DESC")
  end

  def show
    @practices = RunRecord.where(run_class: 0, user_id: params[:id]).order(run_record_day: "DESC").first(5)
    @comp_results = RunRecord.where(run_class: 1, user_id: params[:id])
    @comp_result_recent_five = @comp_results.order(run_record_day: "DESC").first(5)
    @comp_result_maps = CompetitionPlace.set_map(@comp_results)
    @best_time_list = RunRecord.best_time_calc(@comp_results.where(run_distance: [5, 10, 21.0975, 42.195, 100]))
    @user = User.find(params[:id])
    @comp_schedules = @user.competition_infos
    User.run_level_up_decision(@user.id)
  end

  def recent_run_record
    @users = User.all
    @run_records = RunRecord.recent_run_record_find(@users)
  end

end

app/views/users/index.html.haml
%h2= t '.title'

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th= t '.user_name'
        %th= t '.created_at'
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user_path(user)
          %td= user.created_at.strftime("%Y-%m-%d")

= paginate @users

app/views/users/recent_run_record.html.haml
%h2= t '.title'
= render 'shared/recent_contribution_list', run_records: @run_records

app/views/users/show.html.haml
%h1= t('.title', user_name: @user.name)
%h3= t('.run_level')
.red-color
  = @user.run_level
%h3= t('.run_experience')
.red-color
  = @user.total_run_experience
%h3= t '.best_time_list'
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th= t '.best_time_5'
        %th= t '.best_time_10'
        %th= t '.best_time_21'
        %th= t '.best_time_42'
        %th= t '.best_time_100'
    %tbody
      %tr
        - @best_time_list.each do |key, value|
          %td= run_time(value)
%h3= t '.practices_list'
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th= t '.day'
        %th= t '.distance'
        %th= t '.time'
        %th= t '.heart_rate'
        %th= t '.show'
        %th= t '.edit'
        %th= t '.destroy'
    %tbody
      - @practices.each do |practice|
        %tr
          %td= practice.run_record_day
          %td= run_distance(practice)
          %td= run_time(practice)
          %td= practice.body_state.heart_rate
          %td= link_to "#{t '.show'}", practice_run_record_path(practice), class: "btn btn-primary"
          %td= link_to "#{t '.edit'}", edit_practice_run_record_path(practice), class: "btn btn-primary"
          %td= link_to "#{t '.destroy'}", practice_run_record_path(practice), method: :delete, class: "btn btn-primary"
%h3= t ('.comp_schedules')
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th= t '.competition_day'
        %th= t '.competition_name'
        %th= t '.competition_place'
        %th= t '.competition_site'
    %tbody
      - @comp_schedules.each do |comp_schedule|
        %tr
          %td=  comp_schedule.competition_day
          %td=  comp_schedule.competition_name
          %td=  comp_schedule.competition_place
          %td=  link_to comp_schedule.competition_site, "#{comp_schedule.competition_site}", target: "_blank"
%h3= t '.competition_result_list'
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th= t '.competition_day'
        %th= t '.competition_name'
        %th= t '.competition_place'
        %th= t '.distance'
        %th= t '.time'
        %th= t '.competition_point'
        %th= t '.show'
        %th= t '.edit'
        %th= t '.destroy'
    %tbody
      - @comp_result_recent_five.each do |comp_result|
        %tr
          %td= comp_result.run_record_day
          %td= comp_result.competition_place.competition_name
          %td= comp_result.competition_place.competition_place_address
          %td= run_distance(comp_result)
          %td= run_time(comp_result)
          %td= comp_point(comp_result)
          %td= link_to "#{t '.show'}", competition_result_run_record_path(comp_result), class: "btn btn-primary"
          %td= link_to "#{t '.edit'}", edit_competition_result_run_record_path(comp_result), class: "btn btn-primary"
          %td= link_to "#{t '.destroy'}", competition_result_run_record_path(comp_result), method: :delete, class: "btn btn-primary"
%h3= t '.competition_map'
%h5= t '.competition_map_caution'
- unless @comp_result_maps.empty?
  %div(style="width: 100%;")
  #map(style="height: 500px;")
  :javascript
    var mapdata = #{raw @comp_result_maps.to_json};
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(mapdata);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(5);
      });

    $.each(mapdata, function(json, number){
      json.marker = markers[number];
    });

    $.each(mapdata, function(json){
      google.maps.event.addListener(json.marker.getServiceObject(), "click", function() {
        openinfowindow = new google.maps.InfoWindow({
          content: this.serviceObject.infowindow
        });
        openinfowindow.open(this.serviceObject.map, this.serviceObject);
      });
    });
  });