config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  namespace :competition_result do
    resources :run_records
  end
  namespace :practice do
    resources :run_records
  end
  devise_for :users, controllers:{
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks#sns_login"
  }
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :competition_infos, only:[:new, :create, :index] do
    collection do
      get 'search'
    end
  end
  resources :user_comp_schedules, only:[:create]
  resources :boards, shallow: true do
    resources :comments, only:[:create, :edit, :update, :destroy]
  end
  resources :users, only:[:index, :show] do
    collection do
      get 'recent_run_record'
    end
  end
end

app/views/shared/_errors.html.haml
- if object.errors.any?
  #error_explanation.alert.alert-danger
    %ul
    - object.errors.full_messages.each do |msg|
      %li= msg

app/views/shared/_flash.html.haml
- flash.each do |key, value|
  - key = "info" if key == "notice"
  - key = "danger" if key == "alert"
  = content_tag :div, value, class: "alert alert-#{key}"

app/views/shared/_header.html.haml
%nav.navbar.navbar-expand-lg
  %button.navbar-toggler{"data-toggle" => "collapse", :type => "button"}
  .collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item
        %a.nav-link{href: root_path} #{t '.top'}
      %li.nav-item.dropdown
        %a.nav-link.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"} #{t '.mypage'}
        .dropdown-menu
          - if user_signed_in?
            = link_to "#{t '.mypagetop'}", user_path(current_user.id),  class: "dropdown-item"
          = link_to "#{t '.where_run'}", new_competition_result_run_record_path,  class: "dropdown-item"
          = link_to "#{t '.practice_record'}", new_practice_run_record_path,  class: "dropdown-item"
      %li.nav-item.dropdown
        %a.nav-link.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"} #{t '.competition_info_corner'}
        .dropdown-menu
          = link_to "#{t '.get_competition_info'}", new_competition_info_path,  class: "dropdown-item"
          = link_to "#{t '.search_competition'}", competition_infos_path,  class: "dropdown-item"
      %li.nav-item
        %a.nav-link{href: boards_path} #{t '.board'}
    %ul.navbar-nav.ml-auto
      - if user_signed_in?
        %li.nav-item.dropdown
          %a.nav-link.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"} #{t('.welcome_to', name: current_user.name)}
          .dropdown-menu
            = link_to "#{t '.edit_account'}", edit_user_registration_path,  class: "dropdown-item"
            = link_to "#{t '.logout'}", destroy_user_session_path, method: :delete, class: "dropdown-item"
      - else
        %li.nav-item
          = link_to "#{t '.login'}", new_user_session_path

app/views/shared/_recent_contribution_list.html.haml
.table-responsive
  %table.table.table-striped.table-bordered.table-hover.table-sm
    %thead
      %tr
        %th= t '.user_name'
        %th= t '.run_day'
        %th= t '.run_distance'
        %th= t '.run_time'
    %tbody
      - run_records.each do |key, run_record|
        %tr
          %td= link_to run_record.user.name, user_path(run_record.user.id)
          %td= run_record.run_record_day
          %td= run_distance(run_record)
          %td= run_time(run_record)

app/views/shared/_run_record.html.haml
.col-sm-6
  = form_with(model: object, url: path) do |f|
    = render 'shared/errors', object: object
    .field
      %h4= f.label :"#{t '.run_day'}"
      = f.date_select :run_record_day,
        {start_year: Time.now.year - 1, end_year: Time.now.year},
        {class: "form-control bootstrap-date"}
    - if controller.controller_path == "competition_result/run_records"
      = f.fields_for :competition_place do |comp_place_fields|
        .field
          %h4= f.label :"#{t '.competition_name'}"
          = comp_place_fields.text_field :competition_name, class: "form-control"
        .field
          %h4= f.label :"#{t '.competition_start_place'}"
          = comp_place_fields.text_field :competition_place_address, class: "form-control", placeholder:"[スタート地点 or 都道府県市区町]名を入力してください。"
    = f.fields_for :weather_condition do |weather_fields|
      .field
        %h4= f.label :"#{t '.weather_conditions'}"
        %h5= f.label :"#{t '.weather'}"
        = weather_fields.text_field :day_weather, class: "form-control"
        %h5= f.label :"#{t '.temperature'}"
        = weather_fields.text_field :day_temperature, placeholder: "℃", step: "0.1", class: "form-control"
      .field
        %h5= f.label :"#{t '.humidity'}"
        = weather_fields.text_field :day_humidity, placeholder: "%", step: "0.1", class: "form-control"
        %h5= f.label :"#{t '.wind_speed'}"
        = weather_fields.text_field :day_wind_speed, placeholder: "m/s", step: "0.1", class: "form-control"
    .field
      %h4= f.label :"#{t '.run_distance'}"
      %h5= "#{t ".distance_caution"}"
      = f.number_field :run_distance, placeholder: "km", step: "0.0001", class: "form-control",min:0
    .field
      %h4= f.label :"#{t '.run_time'}"
      = f.number_field :run_hour, class: "form-control", min:0
      時間
      \#{f.number_field :run_minute, class: "form-control", min: 0 ,max: 60}分
      \#{f.number_field :run_second, class: "form-control", min: 0 ,max: 60}秒
    = f.fields_for :body_state do |body_fields|
      .field
        %h4= f.label :"#{t '.heart_rate'}"
        = body_fields.number_field :heart_rate, class: "form-control"
      .field
        %h4= f.label :"#{t '.weight'}"
        = body_fields.number_field :day_weight, placeholder: "kg", step: "0.1", class: "form-control"
      .field
        %h4= f.label :"#{t '.body_fat'}"
        = body_fields.number_field :day_body_fat, placeholder: "%", step: "0.1", class: "form-control"
    .field
      %h4= f.label :"#{t '.run_content'}"
      = f.text_area :run_content, rows: "5" , class: "form-control"
      - if controller.controller_path == "competition_result/run_records"
        = f.fields_for :competition_evaluation do |eva_fields|
          .field
            %h4= f.label :"#{t '.competition_point'}"
            = eva_fields.number_field :competition_point, class: "form-control", placeholder: "点数", min: 0, max: 100
          .field
            %h4= f.label :"#{t '.competition_evaluation'}"
            = eva_fields.text_area :competition_evaluation, rows: "3", class: "form-control"
    .button-field
      = f.submit "#{t '.record'}", class: "btn btn-primary btn-block"

app/views/shared/_run_result.html.haml
.table-responsive
  %table.table.table-striped.table-hover.table-bordered
    %body
      %tr
        %td= t '.run_day'
        %td= show_result.run_record_day
      %tr
        %td= t '.run_distance'
        %td= run_distance(show_result)
      %tr
        %td= t '.run_time'
        %td= run_time(show_result)
      %tr
        %td= t '.weather'
        %td= show_result.weather_condition.day_weather
      %tr
        %td= t '.temperature'
        %td= day_temperature(show_result)
      %tr
        %td= t '.humidity'
        %td= day_humidity(show_result)
      %tr
        %td= t '.wind_speed'
        %td= day_wind_speed(show_result)
      %tr
        %td= t '.heart_rate'
        %td= show_result.body_state.heart_rate
      %tr
        %td= t '.weight'
        %td= day_weight(show_result)
      %tr
        %td= t '.body_fat'
        %td= day_body_fat(show_result)
      %tr
        %td= t '.run_content'
        %td= show_result.run_content
      - if controller.controller_path == "competition_result/run_records"
        %tr
          %td= t '.competition_point'
          %td= comp_point(show_result)
        %tr
          %td= t '.competition_evaluation'
          %td= show_result.competition_evaluation.competition_evaluation
= link_to "#{t '.back_to_user_show'}", user_path(show_result.user.id), class: "btn btn-primary"