config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  namespace :competition_result do
    resources :run_records
  end
  namespace :practice do
    resources :run_records
  end
  devise_for :users, controllers:{
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks#sns_login"
  }
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :competition_infos, only:[:new, :create, :index] do
    collection do
      get 'search'
    end
  end
  resources :user_comp_schedules, only:[:create]
  resources :boards, shallow: true do
    resources :comments, only:[:create, :edit, :update, :destroy]
  end
  resources :users, only:[:index, :show] do
    collection do
      get 'recent_run_record'
    end
  end
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :comments, associated: true
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board, only:[:edit, :show, :update, :destroy]

  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to boards_path, notice: t('flash.board.create')
    else
      render :new
    end
  end

  def show
    @comments = @board.comments.all
    @comment = @board.comments.build
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to board_path(@board), notice: t('flash.board.update')
    else
      render :edit
    end
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:user_id, :title)
  end
end

app/views/boards/_form.html.haml
.col-sm-6
  = form_for(@board) do |f|
    = render 'shared/errors', object: @board 
    .field
      = f.label :title
      = f.text_field :title, class: "form-control"
      = f.hidden_field :user_id, value: current_user.id
    .button-field
    = f.submit "#{t '.board_create'}", class: "btn btn-primary btn-block"

app/views/boards/edit.html.haml
%h2= t '.title'
= render 'form'

app/views/boards/index.html.haml
%h2= t '.title'
= link_to "#{t '.create_new_thread'}", new_board_path, class: "btn btn-primary"

.table-responsive
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th= t '.thread_title'
        %th= t '.created_at'
    %tbody
      - @boards.each do |board|
        %tr
          %td= link_to "#{board.title}", board_path(board)
          %td= board.created_at.strftime("%Y-%m-%d")

app/views/boards/new.html.haml
%h2= t '.title'
= render 'form'

app/views/boards/show.html.haml
.col-sm-6
  %h2= t '.title'
  = link_to "#{t '.edit_title'}", edit_board_path(@board)
  = link_to "#{t '.back_to_index'}", boards_path
  .thread-title
    = @board.title
  %hr
  - @comments.each_with_index do |comment, i|
    .field
      = "#{i+1}"
      = ":"
      = comment.user_name
      = comment.created_at.strftime("%Y-%m-%d %H:%M:%S")
      - if current_user.id == comment.user_id
        = link_to "#{t '.edit'}", edit_comment_path(comment)
        = link_to "#{t '.delete'}", comment_path(comment), method: :delete
    .field
      = comment.content
    %hr

  = render 'comments/form'